package harness

import (
	"path"
	"strings"

	"github.com/c0dn/ocws/internal/model"
)

// OpenCode V2 no longer loads custom tools from .opencode/tools/*.ts (the V1
// `tool()` API from @opencode-ai/plugin). For V2, ocws adds one generated
// plugin per tool file under .opencode/plugins/ that imports the unchanged
// V1 module and registers its tools through the V2 plugin API, under the
// same names V1 uses (<file> for a default export, <file>_<export> for named
// ones), so permission rules keep matching.

// RenderToolShim renders the V2 plugin for one V1 tool file.
const RenderToolShim = "opencode-tool-shim"

const toolShimPrefix = ".opencode/plugins/ocws-tool-"

// ToolShims returns the V2 plugin files for a pack's OpenCode tool files.
func ToolShims(files []model.FilePlan) []model.FilePlan {
	var out []model.FilePlan
	for _, f := range files {
		name, ok := toolFileName(f.Destination)
		if !ok {
			continue
		}
		out = append(out, model.FilePlan{Source: f.Source, Destination: toolShimPrefix + name + ".ts",
			Managed: f.Managed, Role: "support", Render: RenderToolShim})
	}
	return out
}

func toolFileName(dest string) (string, bool) {
	if path.Dir(dest) != ".opencode/tools" || strings.HasSuffix(dest, ".d.ts") {
		return "", false
	}
	base := path.Base(dest)
	for _, ext := range []string{".ts", ".js"} {
		if strings.HasSuffix(base, ext) {
			return strings.TrimSuffix(base, ext), true
		}
	}
	return "", false
}

func renderToolShim(dest string) []byte {
	file := strings.TrimSuffix(strings.TrimPrefix(dest, toolShimPrefix), ".ts")
	return []byte(strings.ReplaceAll(toolShimSource, "__FILE__", file))
}

// The shim is dependency-free (V2 resolves no packages for local plugins);
// it installs @opencode-ai/plugin into .opencode on first load, as V1 did.
const toolShimSource = `// Generated by ocws. OpenCode V2 no longer loads .opencode/tools/*.ts, so this
// plugin registers the V1 custom tool file ../tools/__FILE__.ts with the V2
// plugin API. Edit the tool file, not this one.
import { execFileSync } from "node:child_process"
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const FILE = "__FILE__"
const root = dirname(dirname(fileURLToPath(import.meta.url)))

function ensureDependencies() {
  const marker = join(root, "node_modules", "@opencode-ai", "plugin", "package.json")
  if (existsSync(marker)) return
  const lock = join(root, ".ocws-install.lock")
  const sleep = new Int32Array(new SharedArrayBuffer(4))
  for (let i = 0; i < 1200; i++) {
    try {
      mkdirSync(lock)
      break
    } catch {
      if (existsSync(marker)) return
      Atomics.wait(sleep, 0, 0, 100)
    }
  }
  try {
    if (!existsSync(marker)) {
      execFileSync("npm", ["install", "--prefix", root, "--no-save", "--no-package-lock", "--no-audit", "--no-fund", "@opencode-ai/plugin@1"], { stdio: "ignore" })
    }
    // Keep the installed dependencies out of git, as OpenCode V1 does.
    const ignore = join(root, ".gitignore")
    if (!existsSync(ignore)) writeFileSync(ignore, "node_modules\npackage.json\npackage-lock.json\nbun.lock\n.gitignore\n")
  } finally {
    rmSync(lock, { recursive: true, force: true })
  }
}

export default {
  id: "ocws-tool-" + FILE,
  async setup(ctx) {
    ensureDependencies()
    const { tool } = await import("@opencode-ai/plugin")
    const z = tool.schema
    const ts = join(root, "tools", FILE + ".ts")
    const mod = await import(existsSync(ts) ? ts : join(root, "tools", FILE + ".js"))
    const defs = Object.entries(mod).filter(
      ([, v]) => v && typeof v === "object" && typeof v.execute === "function" && v.args && typeof v.args === "object",
    )
    await ctx.tool.transform((editor) => {
      for (const [exported, def] of defs) {
        const schema = z.object(def.args)
        // "input" keeps .default()/.optional() fields optional, as callers see them.
        const input = z.toJSONSchema(schema, { io: "input" })
        delete input.$schema
        editor.add({
          name: exported === "default" ? FILE : FILE + "_" + exported,
          description: def.description ?? "",
          input,
          execute: async (raw, context) => {
            const location = ctx.location ?? {}
            const directory = location.directory ?? process.cwd()
            const result = await def.execute(schema.parse(raw ?? {}), {
              directory,
              worktree: location.project?.directory ?? directory,
              sessionID: context?.sessionID,
              messageID: context?.messageID,
              agent: context?.agent,
              abort: context?.signal ?? new AbortController().signal,
              metadata: (value) => {
                try {
                  context?.progress?.({ status: value?.title ?? "" })
                } catch {}
              },
              ask: async () => {},
            })
            return { content: typeof result === "string" ? result : (result?.output ?? JSON.stringify(result)) }
          },
        })
      }
    })
  },
}
`
